[tool.ruff]
line-length = 79
target-version = "py310"
select = ["E", "F", "I"]
ignore = []

[tool.ruff.isort]
known-first-party = ["data", "ml", "frontend"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--cov=. --cov-report=term-missing"
